version: "3.9"

networks:
  app_network:

services:


  cadvisor:
      image: gcr.io/cadvisor/cadvisor:v0.47.0 
      container_name: cadvisor
      restart: unless-stopped
      privileged: true
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
        - /dev/disk/:/dev/disk:ro
      networks:
        - app_network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - product_service
      - order_service
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 10s
      timeout: 5s
      retries: 3

  auth_service:
    build: ./services/auth_service
    command: uvicorn main_auth_service:app --host 0.0.0.0 --port 8000
    restart: unless-stopped
    environment:
      - DB_HOST=postgres
    ports:
      - "8001:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 5s
      retries: 3

  user_service:
    build: ./services/user_service
    command: uvicorn main_user_service:app --host 0.0.0.0 --port 8000
    restart: unless-stopped
    environment:
      - DB_HOST=postgres
    ports:
      - "8002:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 5s
      retries: 3

  product_service:
    build: ./services/product_service
    container_name: product_service
    restart: unless-stopped
    environment:
      - DB_HOST=postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network
    ports:
      - "8003:8000"   
    command: uvicorn main_product_service:app --host 0.0.0.0 --port 8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 5s
      retries: 3

  order_service:
      build: ./services/order_service
      restart: unless-stopped
      command: uvicorn main_order_service:app --host 0.0.0.0 --port 8000
      environment:
        - DATABASE_URL=postgresql://postgres:1234@postgres:5432/store
     
      depends_on:
        postgres:
          condition: service_healthy
      networks:
        - app_network
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
        interval: 15s
        timeout: 5s
        retries: 3

  chat_service:
    build: ./services/chat_service
    command: uvicorn main_chat_service:app --host 0.0.0.0 --port 8000
    restart: unless-stopped
    ports:
      - "8005:8000"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 5s
      retries: 3

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: store
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "5433:5432"
    networks:
      - app_network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.listen-address=0.0.0.0:9090"
    networks:
      - app_network

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - app_network
